# 入出力
inputDir: "sample/input"
outputDir: "sample/output"
# 行インデックス
lineIdx_templateFileName: 1
lineIdx_sampleMail: 4
# 列インデックス
# 　VMファイル名関連行
colIdx_templateFileName: 8
colIdx_templateFileType: 9
# 　サンプルメール関連行
colIdx_sampleMail_no: 0
colIdx_sampleMail_example: 2
# 　表示仕様関連行
colIdx_displaySpecification_no: 5
colIdx_displaySpecification_explain: 6
colIdx_displaySpecification_targetStr: 7
colIdx_displaySpecification_convertStr: 8
colIdx_displaySpecification_convertType: 9
# 　出し分け仕様関連行
colIdx_separateOutSpecification_no: 5
colIdx_separateOutSpecification_explain: 6
colIdx_separateOutSpecification_condition: 7
colIdx_separateOutSpecification_systemConvertStrTarget: 8
colIdx_separateOutSpecification_systemExpression: 9
colIdx_separateOutSpecification_newLineExists: 10
# 解析行判定マーキング用
markingString_displaySpecification: "表示仕様"
markingString_separateOutSpecification: "出し分け仕様"
# その他
# 　インクルードを表す置換変数の一部
includeConvertStr: "$INCLUDE$"
# 　VMの種別が「本体」の場合の文字列
templateFileTypeMain: "本体"
# 　出力ファイルの拡張子
outputFileSuffix: ".vm"
# 　VMファイルのインクルード時のパス
includeVMpath: "mail/template/parts/"
# 　差し込みファイルを表す置換変数の一部
plubTextStr: "$PLUGTEXT$"
